// AUTO-GENERATED by scripts/build-knowledge.mjs — do not edit by hand.
// Sources: 42 milestones, 18 curated cards, 0 chunks from knowledge/sources/.
// Rebuild after changing curated cards or adding files to knowledge/sources/:
//   node scripts/build-knowledge.mjs
//
// Generated: 2026-06-10T06:04:46.450Z

export const KNOWLEDGE = [
  {
    "id": "milestone-0-3-cognitive",
    "title": "Cognitive (0-3 months): Begins learning through sights, sounds, touch, and routines",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "0-3 months",
      "begins",
      "learning",
      "through",
      "sights",
      "sounds",
      "touch",
      "routines"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Pathways.org, Child Development Institute",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Newborn learning starts with sensory experiences and repeated caregiving rhythms. Babies begin to notice faces, voices, touch, temperature, and comfort cues, which is why calm, responsive care is part of early brain-building. Signs you may notice: Looks toward faces or voices; Briefly tracks nearby objects; Calms with familiar routines or gentle sensory input. Things to try: Hold your baby close and narrate what you are doing; Offer high-contrast objects during short awake windows; Pause after sounds so your baby can respond."
  },
  {
    "id": "milestone-0-3-social",
    "title": "Social-emotional (0-3 months): Looks for safety, comfort, and familiar people",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "0-3 months",
      "looks",
      "safety",
      "comfort",
      "familiar",
      "people"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "NAEYC, ZERO TO THREE, Pathways.org",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Young infants are seeking security. Consistent responses to cries, hunger, tiredness, and overstimulation help babies build trust in caregivers and expectations that people will help them. Signs you may notice: Quiets when picked up or rocked; Turns toward a familiar voice; Shows distress and comfort through body tone, crying, and facial expression. Things to try: Respond promptly and warmly to cries; Use predictable feeding and sleep routines when possible; Let your face be the toy: smile, soften your voice, and wait."
  },
  {
    "id": "milestone-0-3-motor",
    "title": "Motor (0-3 months): Builds early head, eye, hand, and body control",
    "tags": [
      "motor",
      "milestone",
      "development",
      "0-3 months",
      "builds",
      "early",
      "head",
      "hand",
      "body",
      "control"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Early motor development includes lifting the head during tummy time, bringing hands toward the mouth, opening and closing fists, and moving arms and legs with increasing purpose. Signs you may notice: Lifts head briefly on tummy; Moves arms and legs when excited; Brings hands near mouth; Keeps head more upright when supported. Things to try: Place your baby on their tummy while awake and watched; Put a toy just to the side to encourage turning; Support sitting against your chest for a new view."
  },
  {
    "id": "milestone-0-3-language",
    "title": "Language (0-3 months): Communicates with cries, coos, and body signals",
    "tags": [
      "language",
      "milestone",
      "development",
      "0-3 months",
      "communicates",
      "with",
      "cries",
      "coos",
      "body",
      "signals"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Child Development Institute",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Language begins before words. Babies cry, coo, grunt, gaze, and move their bodies to communicate needs and interest, while back-and-forth caregiver talk lays the foundation for later speech. Signs you may notice: Cries differently for different needs; Coos or makes soft sounds; Reacts to voice and sound. Things to try: Copy your baby's sounds as a conversation; Sing the same short song during diaper changes; Describe feelings: You sound hungry. I hear you.."
  },
  {
    "id": "milestone-0-3-sensory-regulation",
    "title": "Sensory & regulation (0-3 months): Learns early calming through touch, sound, and predictable care",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "0-3 months",
      "learns",
      "early",
      "calming",
      "through",
      "touch",
      "sound",
      "predictable",
      "care"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE, NAEYC",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Regulation begins with co-regulation. Newborns depend on caregivers to help them organize sleep, feeding, movement, sound, light, and comfort while their nervous system is still immature. Signs you may notice: Calms with rocking, holding, gentle sound, or sucking; Startles or fusses with sudden sensory changes; Shows sleep-wake patterns that are still developing. Things to try: Dim lights and reduce noise when your baby seems overloaded; Use steady touch, swaddling when safe, or rhythmic rocking; Watch for pause cues such as looking away or stiffening."
  },
  {
    "id": "milestone-0-3-adaptive",
    "title": "Adaptive skills (0-3 months): Participates in early feeding, sleep, and care routines",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "0-3 months",
      "participates",
      "early",
      "feeding",
      "sleep",
      "care",
      "routines"
    ],
    "ageBands": [
      "0-3 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Child Development Institute, NAEYC",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Self-help skills start as tiny participation in caregiving routines. Feeding, diapering, bathing, dressing, and sleep routines teach babies that daily care is predictable and responsive. Signs you may notice: Signals hunger, fullness, tiredness, or discomfort; Begins to settle into repeated care routines; Uses sucking, gaze, crying, or body movement to communicate needs. Things to try: Use the same short words during repeated routines; Pause during feeding to watch for fullness cues; Create a simple wind-down routine before sleep."
  },
  {
    "id": "milestone-4-6-cognitive",
    "title": "Cognitive (4-6 months): Explores cause and effect with hands and mouth",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "4-6 months",
      "explores",
      "cause",
      "effect",
      "with",
      "hands",
      "mouth"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "At this age, babies examine objects by looking, mouthing, grasping, shaking, and repeating actions. This play is problem-solving practice, not random fiddling. Signs you may notice: Reaches for toys; Explores toys with hands and mouth; Looks for interesting sounds or movement; Repeats actions that get a response. Things to try: Offer safe objects with different textures; Play gentle turn-taking games with rattles; Let your baby safely mouth clean teething toys."
  },
  {
    "id": "milestone-4-6-social",
    "title": "Social-emotional (4-6 months): Shows delight in people and familiar play",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "4-6 months",
      "shows",
      "delight",
      "people",
      "familiar",
      "play"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "Child Development Institute, NAEYC, ZERO TO THREE",
      "url": "https://childdevelopmentinfo.com/child-development/normaldevelopment/"
    },
    "text": "Babies often become more expressive, enjoying cuddles, smiles, predictable games, and familiar voices. Responsive social play strengthens attachment and attention. Signs you may notice: Smiles or brightens during interaction; Enjoys being cuddled; Responds to playful voices and faces. Things to try: Play peekaboo slowly and warmly; Name emotions you see: You look excited; Let your baby set the pace when they look away."
  },
  {
    "id": "milestone-4-6-motor",
    "title": "Motor (4-6 months): Rolls, reaches, grasps, and supports more weight",
    "tags": [
      "motor",
      "milestone",
      "development",
      "4-6 months",
      "rolls",
      "reaches",
      "grasps",
      "supports",
      "more",
      "weight"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Control grows from head and trunk into arms and hands. Many babies roll, push up on arms, grasp purposefully, and accept weight through legs when held in standing. Signs you may notice: Rolls tummy to back or back to tummy; Pushes up on arms during tummy time; Transfers a toy between hands; Reaches while lying on back or tummy. Things to try: Put toys just out of reach to invite rolling; Give floor time on a firm surface; Offer one toy at midline so both hands can meet."
  },
  {
    "id": "milestone-4-6-language",
    "title": "Language (4-6 months): Experiments with babbling and vowel-like sounds",
    "tags": [
      "language",
      "milestone",
      "development",
      "4-6 months",
      "experiments",
      "with",
      "babbling",
      "vowel-like",
      "sounds"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Child Development Institute",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Babies begin to play with sound, including babbling and vowel-like vocalizations. They are practicing the rhythm of conversation when adults respond and wait. Signs you may notice: Babbles or squeals; Turns toward voices; Makes more sounds when someone talks back. Things to try: Use parentese: warm, clear, sing-song speech; Read sturdy board books even if your baby mouths them; Pause after your baby's sound before answering."
  },
  {
    "id": "milestone-4-6-sensory-regulation",
    "title": "Sensory & regulation (4-6 months): Uses movement, mouth, hands, and familiar routines to organize",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "4-6 months",
      "uses",
      "movement",
      "mouth",
      "hands",
      "familiar",
      "routines",
      "organize"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Babies this age learn through sensory exploration. Mouthing, reaching, rolling, watching, and listening help them understand the world while caregivers help them recover from overstimulation. Signs you may notice: Explores toys with hands and mouth; Enjoys a variety of safe movements; May need help calming after busy play or noisy places. Things to try: Offer one or two toys at a time instead of a crowded play space; Alternate active play with quiet holding or reading; Name sensory experiences: soft blanket, loud truck, warm bath."
  },
  {
    "id": "milestone-4-6-adaptive",
    "title": "Adaptive skills (4-6 months): Joins care routines with stronger head, mouth, and hand control",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "4-6 months",
      "joins",
      "care",
      "routines",
      "with",
      "stronger",
      "head",
      "mouth",
      "hand",
      "control"
    ],
    "ageBands": [
      "4-6 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "As body control improves, babies participate more in everyday care. They may bring hands or objects to mouth, show clearer feeding cues, and become more engaged in bathing, dressing, and sleep routines. Signs you may notice: Brings hands or safe objects to mouth; Shows clearer likes and dislikes during care; Anticipates familiar routines such as feeding or bedtime. Things to try: Let your baby hold a safe teether or cloth during changes; Tell your baby what happens next in the routine; Keep feeding and sleep routines calm and predictable."
  },
  {
    "id": "milestone-7-9-cognitive",
    "title": "Cognitive (7-9 months): Searches, examines, and learns from new positions",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "7-9 months",
      "searches",
      "examines",
      "learns",
      "from",
      "positions"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "As babies sit, crawl, and shift positions, they can inspect the world from more angles. Exploration supports attention, memory, depth perception, and object learning. Signs you may notice: Looks for partially hidden toys; Investigates shapes, sizes, and textures; Explores from sitting, tummy, crawling, or supported standing. Things to try: Hide a toy partly under a cloth; Create a safe basket of household objects; Let your baby reach and choose while you stay nearby."
  },
  {
    "id": "milestone-7-9-social",
    "title": "Social-emotional (7-9 months): Deepens attachment and may prefer familiar people",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "7-9 months",
      "deepens",
      "attachment",
      "prefer",
      "familiar",
      "people"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "NAEYC, Child Development Institute",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Mobile infants are eager to explore, yet attachment remains the secure base. Many babies show strong preferences for familiar caregivers and may be wary of strangers. Signs you may notice: Checks back with caregiver while exploring; Shows attachment to familiar people; May show stranger wariness or separation distress. Things to try: Stay nearby while your baby explores safely; Use goodbye rituals that are brief and predictable; Name familiar people and routines."
  },
  {
    "id": "milestone-7-9-motor",
    "title": "Motor (7-9 months): Sits, reaches, crawls or creeps, and uses hands more precisely",
    "tags": [
      "motor",
      "milestone",
      "development",
      "7-9 months",
      "sits",
      "reaches",
      "crawls",
      "creeps",
      "uses",
      "hands",
      "more",
      "precisely"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Many babies sit without support, move in and out of positions, begin crawling or creeping, and use thumb and fingers to pick up small objects. Signs you may notice: Sits without support; Moves from tummy or back into sitting; Starts crawling or creeping; Uses thumb and pointer finger for small objects. Things to try: Place toys to the side to encourage weight shifting; Keep small choking hazards out of reach; Use soft obstacles like pillows for supervised movement."
  },
  {
    "id": "milestone-7-9-language",
    "title": "Language (7-9 months): Uses sounds, gestures, and attention to communicate",
    "tags": [
      "language",
      "milestone",
      "development",
      "7-9 months",
      "uses",
      "sounds",
      "gestures",
      "attention",
      "communicate"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Pathways.org",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Communication grows as babies combine babbling, facial expression, gaze, reaching, and turn-taking. They also understand familiar words and routines before they can say them. Signs you may notice: Babbles with repeated sounds; Looks when name is called; Uses reach or gaze to ask for help. Things to try: Name what your baby is looking at; Use gestures such as waving and pointing; Repeat simple words during daily routines."
  },
  {
    "id": "milestone-7-9-sensory-regulation",
    "title": "Sensory & regulation (7-9 months): Explores sensory details from sitting, crawling, and standing",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "7-9 months",
      "explores",
      "sensory",
      "details",
      "from",
      "sitting",
      "crawling",
      "standing"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "New positions give babies new sensory information. They compare textures, distance, movement, sounds, and body balance while still needing help returning to calm. Signs you may notice: Investigates shapes, sizes, textures, and sounds; Shows interest in movement and changes in position; May seek caregiver comfort when tired or overwhelmed. Things to try: Create a safe texture basket with fabric, spoons, and soft blocks; Use quiet spaces after stimulating outings; Offer floor play that lets your baby move toward and away from you."
  },
  {
    "id": "milestone-7-9-adaptive",
    "title": "Adaptive skills (7-9 months): Starts helping with feeding and daily transitions",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "7-9 months",
      "starts",
      "helping",
      "with",
      "feeding",
      "daily",
      "transitions"
    ],
    "ageBands": [
      "7-9 months"
    ],
    "source": {
      "label": "NAEYC, Pathways.org",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Self-help growth shows up in small participation: reaching for a spoon, sitting for meals, helping put arms through sleeves, or learning the order of repeated routines. Signs you may notice: Reaches for food, cup, spoon, or caregiver hands; Sits with support during care routines; Begins anticipating familiar transitions. Things to try: Offer a second spoon for practice during meals; Use the same cleanup phrase after eating or play; Give extra time for your baby to help with arms and legs during dressing."
  },
  {
    "id": "milestone-10-12-cognitive",
    "title": "Cognitive (10-12 months): Solves simple problems and understands familiar instructions",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "10-12 months",
      "solves",
      "simple",
      "problems",
      "understands",
      "familiar",
      "instructions"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Near the end of the first year, babies often imitate actions, search for objects, release items into containers, and respond to simple commands. These are early thinking skills. Signs you may notice: Drops or releases objects into containers; Imitates simple actions; Responds to simple commands; Looks for a hidden object. Things to try: Give a container and safe objects to put in and dump out; Ask one-step requests with gestures; Celebrate effort more than getting it right."
  },
  {
    "id": "milestone-10-12-social",
    "title": "Social-emotional (10-12 months): Shows affection, curiosity, and stronger preferences",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "10-12 months",
      "shows",
      "affection",
      "curiosity",
      "stronger",
      "preferences"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "Child Development Institute, NAEYC, ZERO TO THREE",
      "url": "https://childdevelopmentinfo.com/child-development/normaldevelopment/"
    },
    "text": "Babies this age may show affection, fear of strangers, curiosity, frustration, and clear likes or dislikes. These feelings are part of healthy social-emotional growth. Signs you may notice: Shows affection to familiar people; Explores with curiosity; May show fear of strangers; Looks to caregiver for reassurance. Things to try: Offer comfort before encouraging another try; Let your baby choose between two safe toys; Use words for feelings: You wanted that cup."
  },
  {
    "id": "milestone-10-12-motor",
    "title": "Motor (10-12 months): Pulls to stand, cruises, and may take first steps",
    "tags": [
      "motor",
      "milestone",
      "development",
      "10-12 months",
      "pulls",
      "stand",
      "cruises",
      "take",
      "first",
      "steps"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Babies gain control of legs and feet by pulling up, cruising along furniture, standing briefly, squatting, and sometimes taking several independent steps. Signs you may notice: Pulls to stand; Cruises along furniture; Stands alone briefly or takes steps; Squats to pick up a toy. Things to try: Arrange sturdy furniture for cruising; Offer push-and-pull toys only when safe and stable; Let your baby practice barefoot indoors when appropriate."
  },
  {
    "id": "milestone-10-12-language",
    "title": "Language (10-12 months): Understands more words and may say one or two",
    "tags": [
      "language",
      "milestone",
      "development",
      "10-12 months",
      "understands",
      "more",
      "words"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Child Development Institute",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Babies may imitate sounds, respond to simple commands, and say one or two meaningful words. Understanding usually grows faster than spoken vocabulary. Signs you may notice: Says one or two words or word-like sounds; Imitates speech sounds; Responds to simple commands with gestures. Things to try: Pair words with actions: up, more, all done; Read the same favorite book often; Wait expectantly after asking a simple question."
  },
  {
    "id": "milestone-10-12-sensory-regulation",
    "title": "Sensory & regulation (10-12 months): Uses movement and familiar people to manage excitement and frustration",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "10-12 months",
      "uses",
      "movement",
      "familiar",
      "people",
      "manage",
      "excitement",
      "frustration"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Babies close to age one are more mobile and curious, which can bring excitement, frustration, and sensory seeking. Caregiver support helps them practice returning to calm after big moments. Signs you may notice: Enjoys moving between positions and exploring; Looks to caregiver for reassurance; May protest transitions, fatigue, or limits. Things to try: Use simple transition cues such as one more, then all done; Offer heavy, safe play like pushing a sturdy box; Use calm voice and fewer words when your baby is upset."
  },
  {
    "id": "milestone-10-12-adaptive",
    "title": "Adaptive skills (10-12 months): Practices early mealtime and dressing participation",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "10-12 months",
      "practices",
      "early",
      "mealtime",
      "dressing",
      "participation"
    ],
    "ageBands": [
      "10-12 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Adaptive skills emerge as babies use hands, posture, and attention in daily routines. They may finger feed, hold a cup with help, or cooperate more during dressing and washing. Signs you may notice: Finger-feeds soft foods when developmentally ready; Helps by pushing arms or legs during dressing; Releases objects into containers during cleanup play. Things to try: Invite safe finger-feeding practice during meals; Hold clothing open and wait for your baby to push through; Turn cleanup into fill-and-dump practice."
  },
  {
    "id": "milestone-13-18-cognitive",
    "title": "Cognitive (13-18 months): Experiments, imitates, and figures out how things work",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "13-18 months",
      "experiments",
      "imitates",
      "figures",
      "things",
      "work"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Mobile infants are active scientists. They test what happens when they push, pull, stack, dump, scribble, and copy daily routines they see adults doing. Signs you may notice: Stacks two objects or blocks; Takes toys apart and puts objects in containers; Imitates household actions; Experiments with force. Things to try: Offer nesting cups, boxes, and blocks; Invite safe imitation such as wiping a table; Let repeated play happen; repetition is learning."
  },
  {
    "id": "milestone-13-18-social",
    "title": "Social-emotional (13-18 months): Explores independence while still needing a secure base",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "13-18 months",
      "explores",
      "independence",
      "while",
      "still",
      "needing",
      "secure",
      "base"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "NAEYC, Child Development Institute",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Between 8 and 18 months, many children are eager to explore. They may also become upset during separation, showing that independence and dependence often grow together. Signs you may notice: Moves away to explore, then returns; Shows distress during separation; Wants to try simple tasks independently. Things to try: Use short, predictable separation routines; Offer two acceptable choices; Praise effort: You worked hard to try that."
  },
  {
    "id": "milestone-13-18-motor",
    "title": "Motor (13-18 months): Walks more steadily and begins purposeful scribbling",
    "tags": [
      "motor",
      "milestone",
      "development",
      "13-18 months",
      "walks",
      "more",
      "steadily",
      "begins",
      "purposeful",
      "scribbling"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Toddlers often walk independently, climb low furniture, creep up stairs, pull toys while walking, and make lines with crayons as hand skills improve. Signs you may notice: Walks independently and falls less often; Pulls toys while walking; Creeps up stairs; Makes lines on paper with a crayon. Things to try: Create safe low climbing opportunities; Tape paper to the table for big scribbles; Practice walking outside on varied safe surfaces."
  },
  {
    "id": "milestone-13-18-language",
    "title": "Language (13-18 months): Uses first words, gestures, and shared attention",
    "tags": [
      "language",
      "milestone",
      "development",
      "13-18 months",
      "uses",
      "first",
      "words",
      "gestures",
      "shared",
      "attention"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "ZERO TO THREE, Pathways.org",
      "url": "https://www.zerotothree.org/issue-areas/early-development/"
    },
    "text": "Toddlers communicate with a mix of words, gestures, pointing, facial expression, and shared attention. They learn language fastest inside warm daily interactions. Signs you may notice: Uses several words or consistent word-like sounds; Points, reaches, or gestures to communicate; Understands familiar names and routines. Things to try: Expand one word into a short phrase: Ball. Big ball.; Name what your toddler points to; Sing action songs with gestures."
  },
  {
    "id": "milestone-13-18-sensory-regulation",
    "title": "Sensory & regulation (13-18 months): Uses active play and caregiver support to reset",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "13-18 months",
      "uses",
      "active",
      "play",
      "caregiver",
      "support",
      "reset"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Young toddlers often regulate through movement, repetition, and closeness. They may need help moving from active exploration into quieter routines, especially when hungry, tired, or overstimulated. Signs you may notice: Seeks movement like climbing, carrying, pushing, or pulling; Has stronger reactions to transitions or limits; Calms with familiar people, routines, or comfort objects. Things to try: Build movement breaks into the day; Use a short transition song before changes; Offer a quiet corner with a book or comfort item."
  },
  {
    "id": "milestone-13-18-adaptive",
    "title": "Adaptive skills (13-18 months): Wants to help with dressing, feeding, and cleanup",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "13-18 months",
      "wants",
      "help",
      "with",
      "dressing",
      "feeding",
      "cleanup"
    ],
    "ageBands": [
      "13-18 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Toddlers start showing independence in self-help routines. They may try using utensils, drinking from a cup with help, wiping surfaces, carrying items, or helping with clothing. Signs you may notice: Tries to use a spoon, cup, or napkin; Helps with getting dressed or undressed; Imitates simple household routines. Things to try: Give one simple job during cleanup; Offer child-sized utensils and expect mess; Say the next step and wait: arm in, foot up, wipe hands."
  },
  {
    "id": "milestone-19-24-cognitive",
    "title": "Cognitive (19-24 months): Sorts, stacks, pretends, and solves everyday problems",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "19-24 months",
      "sorts",
      "stacks",
      "pretends",
      "solves",
      "everyday",
      "problems"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Toddlers learn through hands-on problem solving. Sorting colors or shapes, stacking blocks, pretending, and trying different ways to reach a goal all show growing thinking skills. Signs you may notice: Sorts simple shapes or colors; Stacks five or more blocks; Uses pretend actions in play; Turns pages one at a time. Things to try: Sort socks, blocks, or spoons by simple categories; Pretend to feed a doll or stuffed animal; Ask what happens next during a familiar routine."
  },
  {
    "id": "milestone-19-24-social",
    "title": "Social-emotional (19-24 months): Shows big feelings while learning limits and identity",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "19-24 months",
      "shows",
      "feelings",
      "while",
      "learning",
      "limits",
      "identity"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "NAEYC, Child Development Institute, Pathways.org",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Toddlers from 16 to 36 months are working on identity and control. Tantrums can appear when wants are strong but regulation and language are still developing. Signs you may notice: Says or shows no, mine, or me; Has tantrums or strong frustration; Imitates others in simple play; Seeks help after trying. Things to try: Name feelings and set calm limits; Offer small jobs such as putting napkins on the table; Use choices within boundaries: red cup or blue cup."
  },
  {
    "id": "milestone-19-24-motor",
    "title": "Motor (19-24 months): Runs, kicks, climbs, and uses hands for everyday tasks",
    "tags": [
      "motor",
      "milestone",
      "development",
      "19-24 months",
      "runs",
      "kicks",
      "climbs",
      "uses",
      "hands",
      "everyday",
      "tasks"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Toddlers become more active, often running, kicking a large ball, climbing low furniture, helping with dressing, taking off clothing, and twisting objects like doorknobs. Signs you may notice: Runs; Kicks a large ball; Climbs on low furniture; Takes off some clothing; Builds a small block tower. Things to try: Set up a safe indoor movement path; Practice kicking a soft ball outdoors; Let your toddler help with dressing one step at a time."
  },
  {
    "id": "milestone-19-24-language",
    "title": "Language (19-24 months): Builds vocabulary and begins combining ideas",
    "tags": [
      "language",
      "milestone",
      "development",
      "19-24 months",
      "builds",
      "vocabulary",
      "begins",
      "combining",
      "ideas"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "Child Development Institute, ZERO TO THREE",
      "url": "https://childdevelopmentinfo.com/child-development/normaldevelopment/"
    },
    "text": "Vocabulary can grow quickly near age two. Children may use many words, understand more than they say, and begin combining words or ideas to control and explore the world. Signs you may notice: Uses many words; Follows simple one-step directions; Begins short phrases; Names familiar people, objects, or actions. Things to try: Use self-talk: I am cutting the apple; Read books with repeated lines; Avoid quizzing; comment on what your toddler notices."
  },
  {
    "id": "milestone-19-24-sensory-regulation",
    "title": "Sensory & regulation (19-24 months): Practices calming after big feelings and busy sensory play",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "19-24 months",
      "practices",
      "calming",
      "after",
      "feelings",
      "busy",
      "sensory",
      "play"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "NAEYC, Child Development Institute, Pathways.org",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Toddlers near age two can have intense feelings because wants, sensory needs, and language are developing unevenly. Regulation grows through repeated adult support, not lectures during the peak of distress. Signs you may notice: Has tantrums or intense reactions; Seeks active play such as running, jumping, kicking, or climbing; May need help with noise, crowds, clothing, or transitions. Things to try: Use fewer words during meltdowns and more teaching afterward; Offer choices like quiet book or push wall; Preview sensory-heavy events with simple language."
  },
  {
    "id": "milestone-19-24-adaptive",
    "title": "Adaptive skills (19-24 months): Builds self-help confidence through repeated daily jobs",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "19-24 months",
      "builds",
      "self-help",
      "confidence",
      "through",
      "repeated",
      "daily",
      "jobs"
    ],
    "ageBands": [
      "19-24 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Many toddlers want to do parts of care routines themselves. They may remove clothing, help wash hands, use utensils with spills, and participate in cleanup with simple one-step directions. Signs you may notice: Takes off some clothing; Helps wash hands; Uses spoon, cup, or napkin with support; Follows a simple cleanup direction. Things to try: Use a stool and hand-over-hand help for handwashing; Let your toddler put laundry in a basket; Break routines into one visible step at a time."
  },
  {
    "id": "milestone-25-36-cognitive",
    "title": "Cognitive (25-36 months): Plans play, remembers routines, and compares objects",
    "tags": [
      "cognitive",
      "milestone",
      "development",
      "25-36 months",
      "plans",
      "play",
      "remembers",
      "routines",
      "compares",
      "objects"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "Pathways.org, ZERO TO THREE, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Older toddlers show more flexible thinking. They pretend with sequences, remember familiar routines, sort by simple features, and start understanding ideas like one more, big, little, same, and different. Signs you may notice: Sorts shapes and colors; Knows at least one color; Builds taller block towers; Pretend play includes simple sequences. Things to try: Ask open prompts: What should happen next?; Cook together with safe pouring and stirring; Compare objects during cleanup: big truck, small truck."
  },
  {
    "id": "milestone-25-36-social",
    "title": "Social-emotional (25-36 months): Practices independence, humor, empathy, and self-control",
    "tags": [
      "social-emotional",
      "milestone",
      "development",
      "25-36 months",
      "practices",
      "independence",
      "humor",
      "empathy",
      "self-control"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "NAEYC, Child Development Institute",
      "url": "https://www.naeyc.org/resources/topics/dap/infants-and-toddlers"
    },
    "text": "Toddlers this age are building identity and may test limits while also showing humor, affection, awareness of others' feelings, and the ability to play near or with other children. Signs you may notice: Insists on doing some tasks alone; Differentiates facial expressions such as anger, sorrow, and joy; Uses humor or playful tricks; Needs help recovering from big feelings. Things to try: Give language for repair: I was mad. I can try again.; Invite simple helping jobs; Read books about feelings and point to faces."
  },
  {
    "id": "milestone-25-36-motor",
    "title": "Motor (25-36 months): Jumps, pedals, balances, scribbles, and manipulates objects",
    "tags": [
      "motor",
      "milestone",
      "development",
      "25-36 months",
      "jumps",
      "pedals",
      "balances",
      "scribbles",
      "manipulates",
      "objects"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Many two- and three-year-olds jump with both feet, ride or push a tricycle, catch or kick large balls, use crayons, turn pages, string large beads, and pour with support. Signs you may notice: Jumps with both feet leaving the ground; Stands on tiptoes; Catches or kicks large balls; Uses crayons; Pours liquid from a small pitcher with help. Things to try: Draw vertical and circular marks together; Play stop-and-go movement games; Use chunky beads, play dough, and tongs for hand strength."
  },
  {
    "id": "milestone-25-36-language",
    "title": "Language (25-36 months): Uses short sentences to explain wants, ideas, and play",
    "tags": [
      "language",
      "milestone",
      "development",
      "25-36 months",
      "uses",
      "short",
      "sentences",
      "explain",
      "wants",
      "ideas",
      "play"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "Child Development Institute, ZERO TO THREE",
      "url": "https://childdevelopmentinfo.com/child-development/normaldevelopment/"
    },
    "text": "Two- and three-year-olds increasingly use language to explore and control the world. Short sentences, questions, brief storytelling, and temporary stuttering may appear as speech rapidly expands. Signs you may notice: Uses short sentences; Asks or answers simple questions; Names actions and feelings; Uses language during pretend play. Things to try: Add one idea to what your child says; Tell simple stories about the day; Give time to finish thoughts without rushing or correcting every word."
  },
  {
    "id": "milestone-25-36-sensory-regulation",
    "title": "Sensory & regulation (25-36 months): Uses routines, words, and movement to recover from stress",
    "tags": [
      "sensory & regulation",
      "milestone",
      "development",
      "25-36 months",
      "uses",
      "routines",
      "words",
      "movement",
      "recover",
      "from",
      "stress"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "Pathways.org, NAEYC, ZERO TO THREE",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Older toddlers begin using simple strategies for regulation, but still need adult help. Movement games, predictable routines, feeling words, and sensory breaks support self-control over time. Signs you may notice: Uses words or gestures for some needs; Recovers faster with familiar calming routines; May seek or avoid specific sounds, textures, movement, or mess. Things to try: Make a calm-down menu with two or three options; Practice stop-and-go games when your child is already calm; Use feeling words and body words: loud, scratchy, tired, too much."
  },
  {
    "id": "milestone-25-36-adaptive",
    "title": "Adaptive skills (25-36 months): Takes on more dressing, hygiene, feeding, and cleanup steps",
    "tags": [
      "adaptive skills",
      "milestone",
      "development",
      "25-36 months",
      "takes",
      "more",
      "dressing",
      "hygiene",
      "feeding",
      "cleanup",
      "steps"
    ],
    "ageBands": [
      "25-36 months"
    ],
    "source": {
      "label": "Pathways.org, Child Development Institute",
      "url": "https://pathways.org/all-ages/milestones/"
    },
    "text": "Self-help skills become more visible from age two to three. Children may take off clothing, help dress, wash hands, pour with help, use utensils, and follow routines with fewer reminders. Signs you may notice: Takes off simple clothing items; Helps with getting dressed or undressed; Pours liquid from a small pitcher with help; Turns pages, opens containers, or helps clean up. Things to try: Use picture steps for handwashing or bedtime; Offer clothes that are easier to pull on and off; Pour together using a small pitcher over a tray."
  },
  {
    "id": "serve-and-return",
    "title": "Serve and return: everyday back-and-forth builds brain architecture",
    "tags": [
      "serve and return",
      "brain development",
      "language",
      "responsive caregiving",
      "interaction",
      "babbling",
      "attention",
      "connection"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child, Harvard University",
      "url": "https://developingchild.harvard.edu/science/key-concepts/serve-and-return/"
    },
    "text": "Serve and return describes the responsive back-and-forth between a child and a caregiver: a baby coos, points, or reaches (the \"serve\"), and an adult responds in kind with eye contact, words, or a gesture (the \"return\"). These small, contingent exchanges are one of the most important experiences in shaping the architecture of the developing brain. When adults respond reliably to a child's cues, neural connections that support communication, attention, and social skills are built and strengthened. When serves go unreturned again and again, those circuits get less of the input they need. Practically, this means narrating what a child is looking at, naming feelings, pausing to let a baby \"reply\" with a sound or movement, and following the child's focus rather than redirecting it. The interaction does not need to be elaborate or educational — the ordinary rhythm of noticing and responding is the mechanism. This is why responsive, attuned caregiving in the first years matters so much for later learning and emotional health."
  },
  {
    "id": "brain-architecture",
    "title": "Early experience builds brain architecture from the bottom up",
    "tags": [
      "brain development",
      "neural connections",
      "synapses",
      "sensitive periods",
      "early experience",
      "neuroscience",
      "architecture"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child, Harvard University",
      "url": "https://developingchild.harvard.edu/science/key-concepts/brain-architecture/"
    },
    "text": "Brain development in the early years is rapid and experience-dependent. In the first years of life, more than a million new neural connections form every second — a pace never repeated again. Simpler circuits form first and provide the foundation for more complex circuits and skills later, which is why early experiences set the stage for what comes after. Connections are built through the \"serve and return\" interactions a child has with caregivers and the wider environment. The brain is especially plastic early on, meaning experiences shape it most powerfully during sensitive periods, though learning and change remain possible across the lifespan. The implication for parents is reassuring rather than pressuring: children do not need flashcards or enrichment products. They need warm, responsive relationships, language-rich everyday interaction, safe exploration, and protection from chronic stress. Genes provide the basic blueprint, but experience acts like an architect, shaping how that blueprint is actually built."
  },
  {
    "id": "toxic-stress",
    "title": "Positive, tolerable, and toxic stress — and the role of buffering relationships",
    "tags": [
      "stress",
      "toxic stress",
      "cortisol",
      "trauma",
      "adversity",
      "resilience",
      "buffering",
      "co-regulation",
      "nervous system"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child, Harvard University",
      "url": "https://developingchild.harvard.edu/science/key-concepts/toxic-stress/"
    },
    "text": "Not all childhood stress is harmful. Developmental scientists distinguish three types. Positive stress is brief and mild (a first day of childcare) and is a normal, growth-promoting part of development. Tolerable stress is more serious (a loss, an injury) but is time-limited and buffered by supportive adults, so the stress response system returns to baseline. Toxic stress is strong, frequent, or prolonged adversity — such as chronic neglect or exposure to violence — without adequate adult support. Prolonged activation of stress systems in early childhood can disrupt the development of brain architecture and other organ systems. The crucial protective factor is the presence of at least one stable, responsive relationship. Supportive caregivers literally buffer the stress response, helping a child's nervous system recover. This is why co-regulation — a calm adult helping a dysregulated child settle — is not \"giving in,\" but a biological necessity that, repeated over time, builds the child's own capacity to self-regulate."
  },
  {
    "id": "attachment-secure-base",
    "title": "Attachment: the secure base for exploration",
    "tags": [
      "attachment",
      "secure base",
      "bonding",
      "separation",
      "stranger anxiety",
      "trust",
      "Ainsworth",
      "Bowlby",
      "social-emotional"
    ],
    "ageBands": [
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Attachment theory — John Bowlby & Mary Ainsworth"
    },
    "text": "Attachment theory describes the deep emotional bond between a child and their primary caregivers. When a caregiver is consistently available and responsive, the child develops a \"secure base\": they feel safe enough to explore the world and to return for comfort when distressed. Mary Ainsworth's \"Strange Situation\" research described patterns of attachment — secure and several insecure patterns — that relate to how caregivers typically respond to a child's needs. Securely attached children tend to use the caregiver as a base for exploration and are comforted by reunion. Importantly, attachment is built through sensitive, responsive care over time, not through perfection — caregivers naturally misread cues, and that is fine. Separation protest and wariness of strangers, which often emerge in the second half of the first year, are signs of healthy attachment, not problems. The practical takeaway is that responding warmly to a child's bids for comfort builds security; it does not \"spoil\" them or make them clingy."
  },
  {
    "id": "still-face-coregulation",
    "title": "The Still Face: infants need responsive emotional connection",
    "tags": [
      "still face",
      "co-regulation",
      "Tronick",
      "emotion",
      "responsiveness",
      "attunement",
      "repair",
      "social-emotional",
      "connection"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months"
    ],
    "source": {
      "label": "Still Face paradigm — Edward Tronick"
    },
    "text": "In Edward Tronick's \"Still Face\" experiment, a parent first interacts warmly with their baby, then holds a neutral, unresponsive expression. Within seconds, babies work hard to re-engage the parent — smiling, pointing, calling out — and when that fails, they become distressed and withdrawn. When the parent re-engages, the baby quickly recovers. The experiment vividly shows that even very young infants are active social partners who expect and need emotional responsiveness, and that a sudden loss of connection is stressful for them. Just as importantly, Tronick's work introduced the idea of \"rupture and repair\": healthy interactions are not seamless. Caregivers and babies fall out of sync constantly, and the repair — re-establishing connection after a mismatch — is what builds resilience and trust. Parents do not need to be perfectly attuned. They need to keep coming back into connection after the inevitable misses. This reframes ordinary parenting moments: the goal is reconnection, not flawlessness."
  },
  {
    "id": "executive-function",
    "title": "Executive function: working memory, inhibitory control, and flexible thinking",
    "tags": [
      "executive function",
      "self-control",
      "working memory",
      "impulse control",
      "attention",
      "cognitive flexibility",
      "planning",
      "air traffic control"
    ],
    "ageBands": [
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child, Harvard University",
      "url": "https://developingchild.harvard.edu/science/key-concepts/executive-function/"
    },
    "text": "Executive function refers to a set of mental skills the brain uses to plan, focus attention, remember instructions, and juggle tasks — often compared to an \"air traffic control\" system. It rests on three core capacities: working memory (holding information in mind), inhibitory control (resisting impulses and distractions), and cognitive flexibility (shifting between rules or perspectives). Children are not born with these skills; they are born with the potential to develop them, and they grow gradually from infancy into early adulthood, with a major burst in the preschool years. This is why a two-year-old genuinely cannot reliably stop themselves from grabbing a desired object — the inhibitory \"brakes\" are still under construction. Executive function develops through relationships and practice: serve-and-return interaction, predictable routines that reduce cognitive load, and games that exercise memory and self-control (peek-a-boo, Simon Says, sorting games, pretend play). Reducing chronic stress also protects these circuits. Supporting executive function is less about drilling and more about scaffolding — providing structure and gradually handing over control."
  },
  {
    "id": "zone-proximal-development",
    "title": "The zone of proximal development and scaffolding",
    "tags": [
      "scaffolding",
      "zone of proximal development",
      "Vygotsky",
      "learning",
      "support",
      "teaching",
      "play",
      "guided"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Lev Vygotsky — sociocultural theory"
    },
    "text": "Lev Vygotsky proposed that children learn best at the edge of their current ability — in the \"zone of proximal development,\" the space between what a child can do alone and what they can do with help from a more capable partner. Within this zone, a supportive adult or peer provides \"scaffolding\": just enough assistance to let the child succeed at something slightly beyond their independent reach, then gradually withdraws that support as the child gains competence. Practically, scaffolding might mean breaking a task into steps, offering a hint rather than the answer, modeling part of an activity, or holding the structure while the child does the part they can manage. The key is that the support is temporary and responsive — too much help removes the learning, too little leaves the child frustrated. This framework also highlights that much early learning is social: children develop thinking and language through interaction with others, not in isolation. It is the developmental basis for \"guided play\" and responsive teaching."
  },
  {
    "id": "co-regulation-to-self-regulation",
    "title": "Co-regulation comes before self-regulation",
    "tags": [
      "co-regulation",
      "self-regulation",
      "emotion regulation",
      "calming",
      "meltdown",
      "tantrum",
      "name it to tame it",
      "feelings",
      "soothing"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child, Harvard University",
      "url": "https://developingchild.harvard.edu/science/key-concepts/"
    },
    "text": "Self-regulation — the ability to manage one's own emotions, attention, and impulses — is not something young children possess; it is something they build, over years, through thousands of experiences of being regulated by a calm adult. This is co-regulation: when an overwhelmed child borrows a caregiver's steadiness through a soothing voice, calm body, and warm presence until their own nervous system settles. Each time this happens, the child's developing brain practices the path from upset back to calm, and gradually internalizes it. A useful framework is to connect before you correct: a child in the middle of a meltdown is not in a state to reason or learn, because the thinking part of the brain comes back online only after the alarm has quieted. Naming the feeling out loud (\"you're so frustrated that it broke\") helps a child link words to internal states — sometimes called \"name it to tame it.\" Teaching, limits, and problem-solving land better once connection is re-established, not during the peak of distress."
  },
  {
    "id": "temperament-goodness-of-fit",
    "title": "Temperament and goodness of fit",
    "tags": [
      "temperament",
      "personality",
      "goodness of fit",
      "shy",
      "slow to warm",
      "sensitive",
      "active",
      "Thomas",
      "Chess",
      "individual differences"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Temperament research — Alexander Thomas & Stella Chess"
    },
    "text": "Children arrive with their own temperament — a biologically based style of responding to the world that shows up early and tends to be fairly stable. Classic research by Thomas and Chess described dimensions such as activity level, regularity, approach or withdrawal to new things, intensity of reaction, sensitivity, and adaptability, and grouped many children loosely as \"easy,\" \"slow to warm up,\" or \"feisty/difficult.\" No temperament is better or worse; each has strengths. The most useful idea from this work is \"goodness of fit\": children thrive when the demands and expectations of their environment match their temperament. A cautious, slow-to-warm child does best with gentle, gradual introductions to new situations rather than being pushed; a highly active child needs more outlets for movement. Behavior that looks like a \"problem\" is often a mismatch between a child's natural style and what is being asked of them. This reframes parenting away from changing the child and toward adjusting the environment, pace, and expectations to fit who the child actually is."
  },
  {
    "id": "autonomy-toddlerhood",
    "title": "Toddler autonomy: why \"no\" and \"me do it\" are developmental progress",
    "tags": [
      "autonomy",
      "toddler",
      "no",
      "independence",
      "defiance",
      "power struggle",
      "Erikson",
      "will",
      "self",
      "two year old"
    ],
    "ageBands": [
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Erik Erikson — psychosocial development (autonomy vs. shame and doubt)"
    },
    "text": "In Erikson's framework, the central task of toddlerhood is \"autonomy versus shame and doubt.\" Having learned in infancy that the world can be trusted, toddlers turn to a new question: \"Can I act on the world myself?\" Their emphatic \"No!\", their insistence on \"me do it,\" and their resistance to help are not defiance for its own sake — they are a child testing a brand-new sense of being a separate person with their own will. Supporting healthy autonomy means offering real but bounded choices (\"the red cup or the blue cup\"), allowing extra time for a toddler to attempt things themselves, and accepting that big feelings will erupt when their reach exceeds their skill or when limits frustrate them. At the same time, toddlers still need firm, kind limits to feel safe; autonomy is exercised within a secure structure, not without one. When a child's drive for independence is consistently met with warmth and reasonable freedom rather than shaming or excessive control, they emerge with a sense of will and confidence."
  },
  {
    "id": "language-development",
    "title": "How language develops — and why interaction quality matters more than word count",
    "tags": [
      "language",
      "vocabulary",
      "talking",
      "talk",
      "speak",
      "speech",
      "learn to talk",
      "words",
      "conversation",
      "reading",
      "bilingual",
      "word gap",
      "conversational turns",
      "communication",
      "late talker"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Center on the Developing Child / language development research"
    },
    "text": "Language develops through interaction, not exposure alone. Babies move from cooing to babbling to first words (often around the first birthday) to combining words (often in the second year), with wide normal variation. A famous early study (Hart & Risley) drew attention to large differences in how much language children hear — popularized as the \"30-million-word gap.\" Later research has complicated that headline: the raw number of words a child overhears matters far less than the quality of interaction, especially conversational turn-taking — the back-and-forth exchanges where an adult responds to what the child says or attends to. Studies using brain imaging have linked the number of conversational turns, more than sheer word count, to language-related brain activity. Practically, this means talking with a child (not just at or near them): following their gaze, naming what they care about, asking and waiting, reading interactively, and treating babbles as conversation. Bilingual exposure does not cause language delay; bilingual children may mix languages and reach some milestones on their own timeline, which is normal."
  },
  {
    "id": "self-regulation-marshmallow",
    "title": "The marshmallow test, revisited: self-control is contextual, not destiny",
    "tags": [
      "self-control",
      "delay of gratification",
      "marshmallow test",
      "willpower",
      "Mischel",
      "impulse",
      "self-regulation",
      "patience"
    ],
    "ageBands": [
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Delay-of-gratification research — Walter Mischel and later replications"
    },
    "text": "In Walter Mischel's classic experiments, preschoolers were offered one treat now or two if they could wait alone with the first treat. The original work suggested that the ability to delay gratification predicted later outcomes, and the \"marshmallow test\" became shorthand for willpower as a fixed trait. More recent, larger replications (e.g., Watts, Duncan & Quan, 2018) found the link to later outcomes is much weaker than the popular story and is substantially explained by a child's broader environment — economic security, and home circumstances. Equally important, Mischel's own follow-up work showed that \"willpower\" is not a brute force of self-denial: children waited far longer when taught simple strategies, such as distracting themselves or mentally reframing the treat. The lesson for parents is hopeful: self-control in young children is immature by design, varies with how safe and predictable their world feels, and grows through supportive strategies and practice — not through pressure to simply \"try harder.\" A child who cannot wait is showing normal development, not a character flaw."
  },
  {
    "id": "play-based-learning",
    "title": "Learning through play and guided play",
    "tags": [
      "play",
      "guided play",
      "pretend play",
      "learning",
      "imagination",
      "exploration",
      "make believe",
      "free play"
    ],
    "ageBands": [
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Play research — e.g. Kathy Hirsh-Pasek & Roberta Golinkoff"
    },
    "text": "Play is not a break from learning in early childhood — it is a primary engine of it. Through play, children build language, executive function, social skills, and conceptual understanding while practicing at the edge of their abilities. Researchers distinguish free play (child-directed, open-ended) from \"guided play,\" in which an adult sets up an environment or gently steers toward a learning goal while the child keeps agency and initiative. Guided play often produces stronger learning than either purely free play or direct instruction, because it pairs a child's intrinsic motivation with light adult scaffolding. Pretend or symbolic play, which blossoms in the toddler and preschool years, is especially powerful: taking on roles and inventing scenarios exercises self-regulation (following the \"rules\" of the pretend world), perspective-taking, and language. Practically, this means following a child's lead, providing open-ended materials over single-use toys, asking genuine questions, and resisting the urge to turn every moment into a quiz. Children learn deeply when they are absorbed, playful, and socially engaged."
  },
  {
    "id": "sleep-development",
    "title": "How young children's sleep develops",
    "tags": [
      "sleep",
      "night waking",
      "naps",
      "bedtime",
      "routine",
      "sleep regression",
      "self-soothing",
      "circadian",
      "regulation"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Pediatric sleep development (developmental overview)"
    },
    "text": "Sleep is a developmental process. Newborns sleep in short bursts around the clock because their circadian (day–night) rhythm and the hormones that drive it are still maturing; consolidated night sleep typically emerges gradually over the first months as the body clock matures. Night waking is normal at every age — everyone surfaces between sleep cycles — and what changes with development is a child's ability to settle back without help. Predictable, calming bedtime routines act as cues that help a child's nervous system downshift into sleep, and consistency matters more than any single technique. Periods of disrupted sleep (often called \"regressions\") frequently coincide with developmental leaps, such as new motor skills, separation awareness, or language bursts; the brain is busy, and sleep temporarily fragments. Total sleep need decreases and naps consolidate across the early years. Because sleep and emotion regulation share underlying systems, an overtired child often looks dysregulated — more meltdowns, less flexibility — which is a clue to look at sleep rather than only at behavior."
  },
  {
    "id": "screen-time-guidance",
    "title": "Screen time in early childhood: what the evidence and guidelines suggest",
    "tags": [
      "screen time",
      "media",
      "television",
      "tablet",
      "video",
      "displacement",
      "AAP",
      "co-viewing",
      "digital"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "American Academy of Pediatrics — media guidance",
      "url": "https://www.healthychildren.org/English/family-life/Media/Pages/default.aspx"
    },
    "text": "Pediatric guidance focuses less on a single magic number and more on what screens displace and how they are used. For children under about 18–24 months, the American Academy of Pediatrics suggests avoiding screen media other than video-chatting, because the youngest children learn language and skills from responsive real-world interaction and struggle to transfer learning from a 2-D screen (the \"video deficit\"). For ages 2–5, the common recommendation is to limit screen use to roughly an hour a day of high-quality programming, ideally co-viewed so an adult can talk about it and connect it to real life. The deeper principle is displacement: time on screens is time not spent in the serve-and-return interaction, play, movement, and sleep that early development depends on. Background TV also reduces the quantity and quality of parent–child talk. Rather than guilt over occasional use, the useful goals are protecting sleep and mealtimes, keeping media interactive and shared when possible, and ensuring screens do not crowd out the relational experiences children most need."
  },
  {
    "id": "rupture-and-repair",
    "title": "\"Good enough\" parenting: rupture and repair, not perfection",
    "tags": [
      "repair",
      "rupture",
      "good enough",
      "mistakes",
      "apology",
      "Winnicott",
      "Tronick",
      "guilt",
      "reconnection",
      "parenting"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Donald Winnicott (\"good-enough mother\") & Edward Tronick (rupture and repair)"
    },
    "text": "Decades of relational research converge on a freeing idea: children do not need perfect parents, and striving for perfection can even backfire. The pediatrician Donald Winnicott coined \"the good-enough mother\" to describe care that is responsive most of the time and, importantly, fails the child in small, manageable ways — which is exactly how children build resilience and a realistic sense of the world. Tronick's research showed that even in healthy interactions, caregiver and child are \"mismatched\" much of the time; what predicts secure development is not the absence of rupture but the reliable presence of repair. Repair can be simple: returning after you snapped to reconnect, naming what happened (\"I was frustrated and I used a sharp voice — that wasn't about you\"), and re-establishing warmth. This models for children that relationships can bend without breaking, that mistakes are survivable, and that they are still loved after conflict. For parents prone to guilt, the science offers relief: the goal is not to never rupture, but to keep repairing."
  },
  {
    "id": "tantrums-and-the-brain",
    "title": "Tantrums and meltdowns: an immature brain, not manipulation",
    "tags": [
      "tantrum",
      "meltdown",
      "big feelings",
      "amygdala",
      "prefrontal cortex",
      "emotion",
      "anger",
      "crying",
      "behavior",
      "discipline"
    ],
    "ageBands": [
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "Developmental neuroscience of emotion regulation"
    },
    "text": "A tantrum is most accurately understood as a developmental and neurological event, not a strategic one. Young children feel emotions with full intensity, but the prefrontal cortex — the brain region responsible for impulse control, perspective, and calming the alarm system — is highly immature and will keep developing for years. When a toddler is flooded by frustration, fear, or disappointment, the emotional alarm (centered on structures like the amygdala) overwhelms the still-thin \"braking\" system, and the child is genuinely unable to reason, negotiate, or \"calm down\" on command. This is why logic, threats, and long explanations rarely work mid-meltdown — the part of the brain that would receive them is temporarily offline. It also means tantrums are not manipulation; the capacity to manipulate requires exactly the planning skills the child does not yet have. The supportive response is to keep the child (and others) safe, stay calm to co-regulate, keep limits steady but warm, and save teaching for after the storm passes. Tantrums typically become less frequent as language and executive function mature."
  },
  {
    "id": "milestones-are-ranges",
    "title": "Milestones are ranges, and acting early matters when there are concerns",
    "tags": [
      "milestones",
      "development",
      "delay",
      "variation",
      "typical",
      "red flags",
      "early intervention",
      "act early",
      "concern",
      "pediatrician"
    ],
    "ageBands": [
      "0-3 months",
      "4-6 months",
      "7-9 months",
      "10-12 months",
      "13-18 months",
      "19-24 months",
      "25-36 months",
      "3-5 years"
    ],
    "source": {
      "label": "CDC \"Learn the Signs. Act Early.\"",
      "url": "https://www.cdc.gov/ncbddd/actearly/"
    },
    "text": "Developmental milestones describe the average ages by which most children gain a skill — they are ranges, not deadlines. Healthy children vary widely in when they walk, talk, or master a skill, and a child can be ahead in one domain (say, motor) while taking longer in another (say, language). Most variation is simply normal individual difference. At the same time, the evidence on early intervention is clear: when there is a genuine delay, support started earlier tends to be more effective because the young brain is so plastic. So the guidance is twofold and not contradictory. First, resist anxious comparison — a single \"late\" milestone in an otherwise thriving, connected, engaged child is usually not a concern. Second, take persistent patterns seriously: loss of skills a child previously had, no response to their name, very limited eye contact or social engagement, or a consistent lag across several areas are reasons to talk with a pediatrician and ask about evaluation rather than \"waiting to see.\" Trusting parental instinct and seeking assessment is not overreacting; it is exactly what the \"act early\" message encourages."
  }
];
